// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lunchboqs;

namespace content.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190410162431_addedUserSelectionsControllerDataBaseComplete")]
    partial class addedUserSelectionsControllerDataBaseComplete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LunchBoqs.Models.LunchBoq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Entree");

                    b.Property<string>("Name");

                    b.Property<int>("RestaurantId");

                    b.Property<string>("Side1");

                    b.Property<string>("Side2");

                    b.Property<string>("Week");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("LunchBoqs");
                });

            modelBuilder.Entity("LunchBoqs.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("ImgUrl");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("LunchBoqs.Models.UserSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DayOfWeek");

                    b.Property<int>("LunchBoqsId");

                    b.HasKey("Id");

                    b.HasIndex("LunchBoqsId");

                    b.ToTable("UserSelections");
                });

            modelBuilder.Entity("LunchBoqs.Models.LunchBoq", b =>
                {
                    b.HasOne("LunchBoqs.Models.Restaurant", "Restaurant")
                        .WithMany("LunchBoqs")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LunchBoqs.Models.UserSelection", b =>
                {
                    b.HasOne("LunchBoqs.Models.LunchBoq", "LunchBoqs")
                        .WithMany()
                        .HasForeignKey("LunchBoqsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
